version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MongoConnectionString="mongodb+srv://xvruii:HOnI17lAsr2CXd9l@cluster0.aloafkl.mongodb.net/task_trackr_app?retryWrites=true&w=majority"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: "https://task-trackr-app-backend.onrender.com/api"
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=https://task-trackr-app-backend.onrender.com/api
